# Where things are
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'
timezone: Europe/Vilnius

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

sass:
  style: compressed

# Custom
domain: anikevicius.lt
url: http://anikevicius.lt
title: anikevicius.lt
description: Portfolio website of Ignas Anikevičius
copyright: 2017&mdash;2017
name: aignas
author: aignas
twitter:
  username: anikevicius
github:
  username: aignas
theme: jekyll-theme-cayman
show_downloads: false
