base_url = "https://anikevicius.lt"

compile_sass = true
highlight_code = true
highlight_theme = "gruvbox-dark"
build_search_index = true
check_external_links = false
generate_rss = true

[extra]
# Put all your custom variables here
domain = "anikevicius.lt"
copyright = "2017&mdash;2018"
twitter = "anikevicius"
github = "aignas"
name = "aignas"
author = "aignas"
paginate_path = '/blog/page/:num/'
